//Redux constant

export const FETCH_PRODUCTS_DATA = "FETCH_PRODUCTS_DATA";
export const FETCH_PRODUCTS_COUNT = "FETCH_PRODUCTS_COUNT";
export const SET_PRODUCTS_FILTERS = "SET_PRODUCTS_FILTERS";
export const FETCH_PRODUCT_DETAILS_DATA = "FETCH_PRODUCT_DETAILS_DATA";
